version: '3'
services:
  backend:
    image: my-spring-boot-app:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: production
    networks:
      - my-network
  frontend:
    image: my-react-app:latest
    ports:
      - "3000:3000"
    networks:
      - my-network
networks:
  my-network:
