spring.application.name=dict
spring.datasource.url=jdbc:mysql://mysql-3ca5a1d6-tzvetan-7cfa.j.aivencloud.com:13710/dict_app?ssl-mode=REQUIRED

# The username is read from an environment variable. 
# If SPRING_DATASOURCE_USERNAME is not set, it defaults to 'avnadmin'.
spring.datasource.username=${DATASOURCE_USERNAME:avnadmin}

# The password is read from an environment variable. It has no default.
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#Show SQL parameter values
logging.level.org.hibernate.orm.jdbc.bind: trace

# Bind to all network interfaces to allow connections from WSL2
server.address=0.0.0.0

# For WebFlux, force file uploads to be streamed to disk immediately
# by setting a small in-memory buffer.
spring.codec.max-in-memory-size=2KB

# For WebFlux, set the max size for a single file to 1GB
spring.webflux.multipart.max-disk-usage-per-part=1GB

# For WebFlux, set a hard limit on the total number of parts in a request
# to prevent DoS attacks via disk space exhaustion.
spring.webflux.multipart.max-parts=5
